import { ROLES } from '@constants/roles';

export const PERMISSIONS = {
  VIEW_DASHBOARD:      [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  VIEW_REPORTS:        [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  EXPORT_REPORTS:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_CLAIM:          [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  CREATE_CLAIM:        [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DELETE_CLAIM:        [ROLES.SUPER_ADMIN],
  VIEW_CLAIM_SETTINGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_PATIENT:        [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  CREATE_PATIENT:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DELETE_PATIENT:      [ROLES.SUPER_ADMIN],
  VIEW_PAYMENT:        [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  CREATE_PAYMENT:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_DOCUMENTS:      [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.USER],
  UPLOAD_DOCUMENTS:    [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_CUSTOMER_SETUP: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  EDIT_CUSTOMER_SETUP: [ROLES.SUPER_ADMIN],
  VIEW_ACCOUNT_ADMIN:  [ROLES.SUPER_ADMIN],
  MANAGE_USERS:        [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_INTERFACE:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
};
