export const ROUTES = {
  LOGIN:               '/login',
  DASHBOARD:           '/dashboard',
  TASKS:               '/tasks',
  MESSAGES:            '/messages',
  REPORTS:             '/reports',
  APPOINTMENTS:        '/appointments',
  PATIENT:             '/patient',
  CLAIM:               '/claim',
  CLAIM_TRACKER:       '/claim/tracker',
  CLAIM_CONTROL:       '/claim/control',
  FOLLOW_UP:           '/claim/follow-up',
  CLAIM_BATCH_PRINT:   '/claim/batch-print',
  CLAIM_SETTINGS:      '/claim/settings',
  PAYMENT:             '/payment',
  DOCUMENTS:           '/documents',
  INTERFACE:           '/interface',
  CUSTOMER_SETUP:      '/customer-setup',
  ACCOUNT_ADMIN:       '/account-administration',
};
