import {
  Home, BarChart, CalendarMonth, Person, Description,
  Payments, Folder, SwapHoriz, Settings, ManageAccounts,
  Dashboard, Message, Task, Campaign,
  CalendarToday, PlaylistAddCheck, CheckBox, Print, SettingsApplications,
  ManageSearch, Handshake, Assignment, PersonSearch, Receipt,
  LocationOn, Mail, Forum,
  CreditCard, MonetizationOn, Edit, FlashOn, Tune,
  Business, MedicalServices, LocalHospital, SupervisedUserCircle,
  AttachMoney, HealthAndSafety, Code, NotificationImportant,
  Article, MedicalInformation, Label, Build,
} from '@mui/icons-material';
import { ROUTES } from '@constants/routes';

export const NAV_CONFIG = [
  {
    id: 'home',
    label: 'Home',
    icon: Home,
    defaultPath: ROUTES.WELCOME,
    children: [
      { label: 'Welcome',               icon: Home,         path: ROUTES.WELCOME },
      { label: 'Dashboard',             icon: Dashboard,    path: ROUTES.DASHBOARD },
      { label: 'Messages',              icon: Message,      path: ROUTES.MESSAGES },
      { label: 'Tasks...',              icon: Task,         path: ROUTES.TASKS },
      { label: 'Company Announcements', icon: Campaign,     path: ROUTES.COMPANY_ANNOUNCEMENTS },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: BarChart,
    defaultPath: ROUTES.REPORTS,
    children: [],
  },
  {
    id: 'appointments',
    label: 'Appointments',
    icon: CalendarMonth,
    defaultPath: ROUTES.APPOINTMENT_SCHEDULER,
    children: [
      { label: 'Scheduler',             icon: CalendarToday,       path: ROUTES.APPOINTMENT_SCHEDULER },
      { label: 'Manage Waiting List',   icon: PlaylistAddCheck,    path: ROUTES.MANAGE_WAITING_LIST },
      { label: 'Appointment Control',   icon: CheckBox,            path: ROUTES.APPOINTMENT_CONTROL },
      { label: 'Superbill Batch Print', icon: Print,               path: ROUTES.SUPERBILL_BATCH_PRINT },
      { label: 'Configuration...',      icon: SettingsApplications,path: ROUTES.APPOINTMENT_CONFIG },
    ],
  },
  {
    id: 'patient',
    label: 'Patient',
    icon: Person,
    defaultPath: ROUTES.PATIENT_MAIN,
    children: [
      { label: 'Patient',                icon: Person,          path: ROUTES.PATIENT_MAIN },
      { label: 'Manage Account',         icon: ManageSearch,    path: ROUTES.MANAGE_ACCOUNT },
      { label: 'Payment Plans',          icon: Handshake,       path: ROUTES.PAYMENT_PLANS },
      { label: 'A/R Control',            icon: Assignment,      path: ROUTES.AR_CONTROL },
      { label: 'Batch Eligibility',      icon: PersonSearch,    path: ROUTES.BATCH_ELIGIBILITY },
      { label: 'Statement Batch Print',  icon: Receipt,         path: ROUTES.STATEMENT_BATCH_PRINT },
      { label: 'Statement Tracker',      icon: LocationOn,      path: ROUTES.STATEMENT_TRACKER },
      { label: 'Label Batch Print',      icon: Mail,            path: ROUTES.LABEL_BATCH_PRINT },
      { label: 'Communications...',      icon: Forum,           path: ROUTES.COMMUNICATIONS },
      { label: 'Settings',               icon: Settings,        path: ROUTES.PATIENT_SETTINGS, underline: true },
    ],
  },
  {
    id: 'claim',
    label: 'Claim',
    icon: Description,
    defaultPath: ROUTES.CLAIM_MAIN,
    children: [
      { label: 'Claim',               icon: Description, path: ROUTES.CLAIM_MAIN },
      { label: 'Claim Tracker',       icon: LocationOn,  path: ROUTES.CLAIM_TRACKER },
      { label: 'Claim Control',       icon: CheckBox,    path: ROUTES.CLAIM_CONTROL },
      { label: 'Follow Up Management',icon: FlashOn,     path: ROUTES.FOLLOW_UP },
      { label: 'Claim Batch Print',   icon: Print,       path: ROUTES.CLAIM_BATCH_PRINT },
      { label: 'Settings',            icon: Settings,    path: ROUTES.CLAIM_SETTINGS },
    ],
  },
  {
    id: 'payment',
    label: 'Payment',
    icon: Payments,
    defaultPath: ROUTES.PAYMENT_POST,
    children: [
      { label: 'Post',             icon: CreditCard,      path: ROUTES.PAYMENT_POST },
      { label: 'Apply Credit',     icon: MonetizationOn,  path: ROUTES.APPLY_CREDIT },
      { label: 'View',             icon: Edit,            path: ROUTES.PAYMENT_VIEW, underline: true },
      { label: 'ERA',              icon: FlashOn,         path: ROUTES.ERA },
      { label: 'Payment Tracker',  icon: LocationOn,      path: ROUTES.PAYMENT_TRACKER },
      { label: 'Settings',         icon: Tune,            path: ROUTES.PAYMENT_SETTINGS },
    ],
  },
  {
    id: 'documents',
    label: 'Documents',
    icon: Folder,
    defaultPath: ROUTES.DOCUMENTS,
    children: [],
  },
  {
    id: 'interface',
    label: 'Interface',
    icon: SwapHoriz,
    defaultPath: ROUTES.INTERFACE,
    children: [],
  },
  {
    id: 'customerSetup',
    label: 'Customer Setup',
    icon: SettingsApplications,
    defaultPath: ROUTES.PRACTICES,
    children: [
      { label: 'Practices',           icon: Business,            path: ROUTES.PRACTICES },
      { label: 'Providers',           icon: SupervisedUserCircle,path: ROUTES.PROVIDERS },
      { label: 'Facilities',          icon: LocalHospital,       path: ROUTES.FACILITIES },
      { label: 'Referring Providers', icon: MedicalServices,     path: ROUTES.REFERRING_PROVIDERS },
      { label: 'Payers',              icon: AttachMoney,         path: ROUTES.PAYERS },
      { label: 'Payer Agreements',    icon: Handshake,           path: ROUTES.PAYER_AGREEMENTS },
      { label: 'Collection Agencies', icon: HealthAndSafety,     path: ROUTES.COLLECTION_AGENCIES },
      { label: 'Codes...',            icon: Code,                path: ROUTES.CODES },
      { label: 'Alert Control',       icon: NotificationImportant,path: ROUTES.ALERT_CONTROL },
      { label: 'Statements',          icon: Article,             path: ROUTES.STATEMENTS_SETUP },
      { label: 'Superbills',          icon: MedicalInformation,  path: ROUTES.SUPERBILLS },
      { label: 'Labels',              icon: Label,               path: ROUTES.LABELS },
      { label: 'Customization...',    icon: Build,               path: ROUTES.CUSTOMIZATION },
      { label: 'Settings',            icon: Settings,            path: ROUTES.CUSTOMER_SETTINGS },
    ],
  },
  {
    id: 'accountAdmin',
    label: 'Account Administration',
    icon: ManageAccounts,
    defaultPath: ROUTES.ACCOUNT_ADMIN,
    children: [],
  },
];
